package ru.omsu.themoviedb

object Settings {
    const val API_KEY = "f0fc35f5ec87f52edeb0d917655e056f"
    const val URL_TMDB_BASE = "https://image.tmdb.org/t/p/"
    const val BACKDROP_SIZE_W300 = "w300"
    const val BACKDROP_SIZE_W780 = "w780"
    const val BACKDROP_SIZE_W1280 = "w1280"
    const val BACKDROP_SIZE_ORIGINAL = "original"
    const val LOGO_SIZE_W45 = "w45"
    const val LOGO_SIZE_W92 = "w92"
    const val LOGO_SIZE_W154 = "w154"
    const val LOGO_SIZE_W185 = "w185"
    const val LOGO_SIZE_W300 = "w300"
    const val LOGO_SIZE_W500 = "w500"
    const val LOGO_SIZE_ORIGINAL = "original"
    const val POSTER_SIZE_W45 = "w92"
    const val POSTER_SIZE_W92 = "w154"
    const val POSTER_SIZE_W154 = "w185"
    const val POSTER_SIZE_W185 = "w342"
    const val POSTER_SIZE_W300 = "w500"
    const val POSTER_SIZE_W500 = "w780"
    const val POSTER_SIZE_ORIGINAL = "original"
    const val PROFILE_SIZE_W45 = "w45"
    const val PROFILE_SIZE_W185 = "w185"
    const val PROFILE_SIZE_H632 = "h632"
    const val PROFILE_SIZE_ORIGINAL = "original"
    const val STILL_SIZE_W92 = "w92"
    const val STILL_SIZE_W185 = "w185"
    const val STILL_SIZE_W300 = "w300"
    const val STILL_SIZE_ORIGINAL = "original"
    const val URL_YOUTUBE_VIDEO = "http://www.youtube.com/watch?v="
    const val PATH_IMAGE_PERSON_NO_PHOTO = "file:///android_asset/nophoto.png"
    const val PATH_IMAGE_PERSON_NO_POSTER = "file:///android_asset/noposter.png"
    const val PATH_IMAGE_PERSON_NO_STILL = "file:///android_asset/nostill.png"
}